import type { Metadata } from 'next'
import '@/styles/globals.css'
import TanStackProvider from '@/app/providers'
import localFont from 'next/font/local'

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${pretendard.className} antialiased`}>
        <TanStackProvider>{children}</TanStackProvider>
      </body>
    </html>
  )
}
