import type { Metadata } from 'next'
import '@/styles/globals.css'
import { Toaster } from 'react-hot-toast'
import TanStackProvider from '@/app/providers'
import localFont from 'next/font/local'
import Sidebar from '../components/RootLayout/Sidebar'

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${pretendard.className} antialiased`}>
        <TanStackProvider>
          <div className='flex h-screen'>
            <Toaster position='top-center' />
            <Sidebar />
            <div className='grow'>{children}</div>
          </div>
        </TanStackProvider>
      </body>
    </html>
  )
}
