export const URL_PATH = {
  Home: '/',
  Memos: '/memos',
  Group: '/group',
  GroupList: '/groups',
  GroupCreate: '/groups/create',
  Login: '/login',
  LoginSuccess: '/login/success',
  Signup: '/login/signup',
  MemosCreate: '/memos/create',
  MyMemos: '/memos/my',
  TemplateDetail: '/memos/template',
}

export const API_PATH = {
  Login: '/auth/oauth2/kakao',
  ReissueToken: '/auth/reissue',
  Signup: '/user/after-login',
  GetMyGroupList: '/user/group/list',
  GetPopularGroupList: '/group/popular',
  GetRecommendGroupList: '/group/recommend',
  GetPublicTemplate: '/template/public',
  GroupCreate: '/group',
  Group: '/group',
  Template: '/template',
  TemplateList: '/template/public',
  // TODO: memo와 retrospect 통일 필요
  Retrospect: '/retrospect',
  RetrospectCreate: '/retrospect/add',
  GetRetrospects: '/retrospect/all',
  GroupList: '/group/list',
  User: '/user',
  RetrospectList: '/retrospect/all',
  Comment: '/comment',
}
