export const URL_PATH = {
  Landing: '/landing',
  Home: '/',
  Retrospects: '/retrospects',
  Group: '/group',
  GroupList: '/groups',
  Profile: '/profile',
  GroupUpdate: '/groups/update',
  GroupCreate: '/groups/create',
  Login: '/login',
  LoginSuccess: '/login/success',
  Signup: '/login/signup',
  RetrospectsCreate: '/retrospects/create',
  MyRetrospects: '/retrospects/my',
  TemplateDetail: '/retrospects/template',
}

export const API_PATH = {
  Login: '/auth/oauth2/kakao',
  ReissueToken: '/auth/reissue',
  Signup: '/user/after-login',
  GetMyGroupList: '/user/group/list',
  GetPopularGroupList: '/group/popular',
  GetRecommendGroupList: '/group/recommend',
  GetPublicTemplate: '/template/public',
  GroupCreate: '/group',
  Group: '/group',
  Template: '/template',
  TemplateList: '/template/public',
  Retrospect: '/retrospect',
  RetrospectCreate: '/retrospect/add',
  GetRetrospects: '/retrospect/all',
  GetMyRetrospects: '/retrospect/member',
  GroupList: '/group/list',
  User: '/user',
  RetrospectList: '/retrospect/all',
  Comment: '/comment',
  GroupJoin: '/group/join',
  MemoCreate: '/memo',
}
